-- Phase 6: two-bucket media architecture for the single PRISM installation.
-- Public marketing assets are intentionally readable by anyone; student and
-- staff photos remain private and are served only through short-lived signed URLs.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('public-school-media', 'public-school-media', true, 8388608, array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/x-icon', 'image/vnd.microsoft.icon']),
  ('private-school-files', 'private-school-files', false, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/avif'])
on conflict (id) do nothing;

-- Anonymous access is read-only and limited to exact server-generated paths.
create policy public_school_media_read on storage.objects for select
  using (
    bucket_id = 'public-school-media'
    and name ~ '^(branding/(logo|og)/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|branding/favicon/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif|ico)|hero/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|programs/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|services/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|gallery/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif))$'
  );

-- Storage paths are generated by the server action; RLS repeats the allowlist
-- so a forged client request cannot create arbitrary public directories.
create policy public_school_media_insert on storage.objects for insert to authenticated
  with check (
    bucket_id = 'public-school-media'
    and public.has_permission('website_settings.manage')
    and name ~ '^(branding/(logo|og)/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|branding/favicon/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif|ico)|hero/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|programs/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|services/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|gallery/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif))$'
  );
create policy public_school_media_update on storage.objects for update to authenticated
  using (
    bucket_id = 'public-school-media'
    and public.has_permission('website_settings.manage')
    and name ~ '^(branding/(logo|og)/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|branding/favicon/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif|ico)|hero/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|programs/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|services/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|gallery/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif))$'
  )
  with check (
    bucket_id = 'public-school-media'
    and public.has_permission('website_settings.manage')
    and name ~ '^(branding/(logo|og)/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|branding/favicon/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif|ico)|hero/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|programs/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|services/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|gallery/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif))$'
  );
create policy public_school_media_delete on storage.objects for delete to authenticated
  using (
    bucket_id = 'public-school-media'
    and public.has_permission('website_settings.manage')
    and name ~ '^(branding/(logo|og)/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|branding/favicon/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif|ico)|hero/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|programs/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|services/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)|gallery/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif))$'
  );

-- Private mutations require the matching domain edit permission. Reads also
-- permit the linked student/guardian or staff account, without granting broad
-- access to every authenticated user.
create policy private_school_files_insert on storage.objects for insert to authenticated
  with check (
    bucket_id = 'private-school-files'
    and (
      (name ~ '^students/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)$' and public.has_permission('students.edit'))
      or (name ~ '^staff/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)$' and public.has_permission('staff.edit'))
    )
  );
create policy private_school_files_update on storage.objects for update to authenticated
  using (
    bucket_id = 'private-school-files'
    and (
      (name ~ '^students/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)$' and public.has_permission('students.edit'))
      or (name ~ '^staff/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)$' and public.has_permission('staff.edit'))
    )
  )
  with check (
    bucket_id = 'private-school-files'
    and (
      (name ~ '^students/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)$' and public.has_permission('students.edit'))
      or (name ~ '^staff/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)$' and public.has_permission('staff.edit'))
    )
  );
create policy private_school_files_delete on storage.objects for delete to authenticated
  using (
    bucket_id = 'private-school-files'
    and (
      (name ~ '^students/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)$' and public.has_permission('students.edit'))
      or (name ~ '^staff/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)$' and public.has_permission('staff.edit'))
    )
  );
create policy private_school_files_read on storage.objects for select to authenticated
  using (
    bucket_id = 'private-school-files'
    and (
      (name ~ '^students/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)$' and (
        public.has_permission('students.view')
        or exists (
          select 1 from public.students s
          where s.id::text = (storage.foldername(name))[2]
            and (s.user_id = auth.uid() or exists (
              select 1 from public.student_guardians sg
              join public.guardians g on g.id = sg.guardian_id
              where sg.student_id = s.id and g.user_id = auth.uid()
            ))
        )
      ))
      or (name ~ '^staff/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/photos/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.](jpg|png|webp|avif)$' and (
        public.has_permission('staff.view')
        or exists (
          select 1 from public.staff st
          where st.id::text = (storage.foldername(name))[2] and st.user_id = auth.uid()
        )
      ))
    )
  );

alter table public.school_settings add column hero_image_url text;

create table public.website_gallery_items (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 120),
  caption text check (caption is null or char_length(caption) <= 500),
  category text check (category is null or char_length(category) <= 80),
  storage_path text not null unique check (storage_path ~ '^gallery/[0-9a-f-]+[.](jpg|png|webp|avif)$'),
  image_url text not null,
  alt_text text not null check (char_length(alt_text) between 3 and 200),
  display_order integer not null default 0 check (display_order between 0 and 10000),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index website_gallery_items_public_order_idx
  on public.website_gallery_items (display_order, created_at) where is_active;
create trigger website_gallery_items_touch before update on public.website_gallery_items
  for each row execute function public.touch_updated_at();
alter table public.website_gallery_items enable row level security;
create policy website_gallery_items_select on public.website_gallery_items for select
  using (is_active or public.has_permission('website_settings.read'));
create policy website_gallery_items_write on public.website_gallery_items for all
  using (public.has_permission('website_settings.manage'))
  with check (public.has_permission('website_settings.manage'));
grant select on public.website_gallery_items to anon, authenticated;
grant insert, update, delete on public.website_gallery_items to authenticated;

-- Extend the Phase 5 allowlisted RPC instead of widening direct table updates.
create or replace function public.update_website_settings(p_settings jsonb)
returns public.school_settings
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.school_settings;
  allowed_keys constant text[] := array[
    'school_name', 'short_name', 'tagline', 'description', 'logo_url',
    'favicon_url', 'primary_color', 'secondary_color', 'accent_color',
    'hero_eyebrow', 'hero_tagline', 'hero_title', 'hero_description',
    'hero_primary_cta_label', 'hero_primary_cta_url',
    'hero_secondary_cta_label', 'hero_secondary_cta_url', 'hero_image_url',
    'contact_email', 'contact_phone', 'website_url', 'address_line', 'city',
    'district', 'state', 'country', 'postal_code', 'google_maps_url',
    'facebook_url', 'instagram_url', 'youtube_url', 'linkedin_url',
    'seo_title', 'seo_description', 'og_image_url'
  ];
begin
  if not public.has_permission('website_settings.manage') then raise exception 'Forbidden'; end if;
  if p_settings is null or jsonb_typeof(p_settings) <> 'object' then raise exception 'Website settings payload must be an object'; end if;
  if exists (select 1 from jsonb_object_keys(p_settings) supplied(key) where not (supplied.key = any (allowed_keys))) then
    raise exception 'Website settings payload contains unsupported fields';
  end if;
  update public.school_settings s set
    school_name = coalesce(p_settings ->> 'school_name', s.school_name), short_name = case when p_settings ? 'short_name' then p_settings ->> 'short_name' else s.short_name end,
    tagline = coalesce(p_settings ->> 'tagline', s.tagline), description = case when p_settings ? 'description' then p_settings ->> 'description' else s.description end,
    logo_url = case when p_settings ? 'logo_url' then p_settings ->> 'logo_url' else s.logo_url end, favicon_url = case when p_settings ? 'favicon_url' then p_settings ->> 'favicon_url' else s.favicon_url end,
    primary_color = coalesce(p_settings ->> 'primary_color', s.primary_color), secondary_color = coalesce(p_settings ->> 'secondary_color', s.secondary_color), accent_color = coalesce(p_settings ->> 'accent_color', s.accent_color),
    hero_eyebrow = coalesce(p_settings ->> 'hero_eyebrow', s.hero_eyebrow), hero_tagline = coalesce(p_settings ->> 'hero_tagline', s.hero_tagline), hero_title = coalesce(p_settings ->> 'hero_title', s.hero_title), hero_description = coalesce(p_settings ->> 'hero_description', s.hero_description),
    hero_primary_cta_label = coalesce(p_settings ->> 'hero_primary_cta_label', s.hero_primary_cta_label), hero_primary_cta_url = coalesce(p_settings ->> 'hero_primary_cta_url', s.hero_primary_cta_url), hero_secondary_cta_label = coalesce(p_settings ->> 'hero_secondary_cta_label', s.hero_secondary_cta_label), hero_secondary_cta_url = coalesce(p_settings ->> 'hero_secondary_cta_url', s.hero_secondary_cta_url), hero_image_url = case when p_settings ? 'hero_image_url' then p_settings ->> 'hero_image_url' else s.hero_image_url end,
    contact_email = case when p_settings ? 'contact_email' then p_settings ->> 'contact_email' else s.contact_email end, contact_phone = case when p_settings ? 'contact_phone' then p_settings ->> 'contact_phone' else s.contact_phone end, website_url = case when p_settings ? 'website_url' then p_settings ->> 'website_url' else s.website_url end,
    address_line = case when p_settings ? 'address_line' then p_settings ->> 'address_line' else s.address_line end, city = case when p_settings ? 'city' then p_settings ->> 'city' else s.city end, district = case when p_settings ? 'district' then p_settings ->> 'district' else s.district end, state = case when p_settings ? 'state' then p_settings ->> 'state' else s.state end, country = case when p_settings ? 'country' then p_settings ->> 'country' else s.country end, postal_code = case when p_settings ? 'postal_code' then p_settings ->> 'postal_code' else s.postal_code end,
    google_maps_url = case when p_settings ? 'google_maps_url' then p_settings ->> 'google_maps_url' else s.google_maps_url end, facebook_url = case when p_settings ? 'facebook_url' then p_settings ->> 'facebook_url' else s.facebook_url end, instagram_url = case when p_settings ? 'instagram_url' then p_settings ->> 'instagram_url' else s.instagram_url end, youtube_url = case when p_settings ? 'youtube_url' then p_settings ->> 'youtube_url' else s.youtube_url end, linkedin_url = case when p_settings ? 'linkedin_url' then p_settings ->> 'linkedin_url' else s.linkedin_url end,
    seo_title = case when p_settings ? 'seo_title' then p_settings ->> 'seo_title' else s.seo_title end, seo_description = case when p_settings ? 'seo_description' then p_settings ->> 'seo_description' else s.seo_description end, og_image_url = case when p_settings ? 'og_image_url' then p_settings ->> 'og_image_url' else s.og_image_url end,
    updated_by = auth.uid()
  where s.id = 1 returning * into result;
  return result;
end;
$$;

revoke execute on function public.update_website_settings(jsonb) from public, anon;
grant execute on function public.update_website_settings(jsonb) to authenticated;
revoke select (hero_image_url) on public.school_settings from anon;
grant select (hero_image_url) on public.school_settings to anon;
